### ISSUE TITLE
"#_ is deprecated. Require your own version of Lodash or underscore.string"

### ISSUE THREAD

**Issue by MylesShannon** [Freyskeyd/generator-laravel#12]
Node v4.4.6
Yo v1.8.4
MacOS Sierra beta 2
Composer installed

```
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'chain' of undefined
    at LaravelGenerator.rootMenu (/usr/local/lib/node_modules/generator-laravel/app/index.js:23:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-laravel/node_modules/yeoman-generator/lib/base.js:439:23)
    at /usr/local/lib/node_modules/generator-laravel/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-laravel/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-laravel/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by vert3x** [comment]
does anyone found a solution for this ?
